# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI
on:
  push:
    branches: [master] # 將 "master" 更改為 "main"，如果您的主要分支名稱是 "main"
  pull_request:
    branches: [master] # 將 "master" 更改為 "main"，如果您的主要分支名稱是 "main"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 16 # 更新 Node.js 版本為 16
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - run: yarn run lint
      - run: yarn run test --runInBand --no-cache
        env:
          CI: true
